FROM node as build

WORKDIR /app

ENV PORT_API=3030
ENV IP_API=172.20.0.25 
#aucun impact

COPY . .

RUN npm i

RUN npm run build

FROM nginx

COPY --from=build /app/dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]

