FROM node as build

ARG PORT_API
ARG IP_API

WORKDIR /app

ENV PORT_API=${PORT_API}
ENV IP_API=${IP_API}
#aucun impact

COPY . .

RUN npm i

RUN npm run build

FROM nginx

COPY --from=build /app/dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]

